### ISSUE TITLE
Лишний код

### ISSUE THREAD

**Issue by pflb-izh** [mozhg/pl_pr1_hw#1]
https://github.com/mozhg/pl_pr1_hw/blob/6fb1f5f7d1a43890efd72a62c7a4ae36c1af1095/src/com/gmail1/mozhgru/sleepcls/SleepCls.java#L36
1. Зачем if-else, если выражение внутри этого if-else уже возвращает то, что нужно? почему сразу его не вернуть?
2. Зачем в данной ситуации сравнивать boolen с true/false? Можно же сократить все это до вида 
`return weekday || vacation`.

**Comment by duskborn** [comment]
Исправил.
