### ISSUE TITLE
Можно сократить

### ISSUE THREAD

**Issue by pflb-izh** [mozhg/pl_pr1_hw#2]
https://github.com/mozhg/pl_pr1_hw/blob/a32ae95999dd34cbb976fab2fbbe8945d41b29ca/src/com/gmail/mozhgru/sleepcls/SumDoubleCls.java#L24
Для улучшение читаемости убрать else. Ведь операция `a + b` выполняется всегда.

**Comment by duskborn** [comment]
Вроде бы поправил
